//
// Created by Eric on 08.03.2017.
//

#ifndef WORLDPOPULATIONMONITORING_DYNAMICCONTAINER_H
#define WORLDPOPULATIONMONITORING_DYNAMICCONTAINER_H

#include "Country.h"
#include <stdlib.h>





#endif //WORLDPOPULATIONMONITORING_DYNAMICCONTAINER_H

